# 100 pandas puzzles

Inspired by [100 Numpy exerises](https://github.com/rougier/numpy-100), here are 100* short puzzles for testing your knowledge of [pandas'](http://pandas.pydata.org/) power.

Since pandas is a large library with many different specialist features and functions, these excercises focus mainly on the fundamentals of manipulating data (indexing, grouping, aggregating, cleaning), making use of the core DataFrame and Series objects. 

Many of the excerises here are stright-forward in that the solutions require no more than a few lines of code (in pandas or NumPy... don't go using pure Python or Cython!). Choosing the right methods and following best practices is the underlying goal.

The exercises are loosely divided in sections. Each section has a difficulty rating; these ratings are subjective, of course, but should be a seen as a rough guide as to how inventive the required solution is.

If you're just starting out with pandas and you are looking for some other resources, the official documentation  is very extensive. In particular, some good places get a broader overview of pandas are...

- [10 minutes to pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html)
- [pandas basics](http://pandas.pydata.org/pandas-docs/stable/basics.html)
- [tutorials](http://pandas.pydata.org/pandas-docs/stable/tutorials.html)
- [cookbook and idioms](http://pandas.pydata.org/pandas-docs/stable/cookbook.html#cookbook)

Enjoy the puzzles!

\* *the list of exercises is not yet complete! Pull requests or suggestions for additional exercises, corrections and improvements are welcomed.*

## Importing pandas

### Getting started and checking your pandas setup

Difficulty: *easy* 

**1.** Import pandas under the alias `pd`.

In [3]:
# install pandas if missing
#%pip install pandas

import pandas as pd

**2.** Print the version of pandas that has been imported.

In [4]:
pd.__version__

'2.3.3'

**3.** Print out all the *version* information of the libraries that are required by the pandas library.

In [5]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : 9c8bc3e55188c8aff37207a74f1dd144980b8874
python                : 3.9.6
python-bits           : 64
OS                    : Darwin
OS-release            : 25.3.0
Version               : Darwin Kernel Version 25.3.0: Wed Jan 28 20:54:55 PST 2026; root:xnu-12377.91.3~2/RELEASE_ARM64_T8132
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.3.3
numpy                 : 2.0.2
pytz                  : 2026.1.post1
dateutil              : 2.9.0.post0
pip                   : 26.0.1
Cython                : None
sphinx                : None
IPython               : 8.18.1
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2025.3
qtpy                  : None
pyqt5                 : None

## DataFrame basics

### A few of the fundamental routines for selecting, sorting, adding and aggregating data in DataFrames

Difficulty: *easy*

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [6]:
%pip install numpy
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /Users/jirongliu/Library/Python/3.9/lib/python/site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

**5.** Display a summary of the basic information about this DataFrame and its data (*hint: there is a single method that can be called on the DataFrame*).

In [162]:
%pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /Users/jirongliu/Library/Python/3.9/lib/python/site-packages (26.0.1)
Note: you may need to restart the kernel to use updated packages.

**6.** Return the first 3 rows of the DataFrame `df`.

In [163]:
df[:3]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [164]:
df[['animal','age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [165]:
df.loc[:,['animal','age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [166]:
df.head()

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no

**8.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [167]:
cols =['animal','age']
df.iloc[[3,4,8],[df.columns.get_loc(col) for col in cols]]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [168]:
df.loc[df.index[[3,4,8]],['animal','age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [169]:
df.loc['a', 'animal']

'cat'

**9.** Select only the rows where the number of visits is greater than 3.

In [170]:
df[df['visits']>=3]

  animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

In [171]:
df.loc[df["visits"] >=3]

  animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

**10.** Select the rows where the age is missing, i.e. it is `NaN`.

In [172]:
df.loc[df['age'].isnull()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [173]:
df[df['age'].isnull()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** Select the rows where the animal is a cat *and* the age is less than 3.

In [174]:
df[(df['animal'] == 'cat') & (df['age']<3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**12.** Select the rows the age is between 2 and 4 (inclusive).

In [175]:
df[(df['age']>=2)&(df['age']<=4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**13.** Change the age in row 'f' to 1.5.

In [176]:
df.loc['f', 'age'] = 1.5

In [177]:
df.loc[:, 'age']

a    2.5
b    3.0
c    0.5
d    NaN
e    5.0
f    1.5
g    4.5
h    NaN
i    7.0
j    3.0
Name: age, dtype: float64

In [178]:
df['age']

a    2.5
b    3.0
c    0.5
d    NaN
e    5.0
f    1.5
g    4.5
h    NaN
i    7.0
j    3.0
Name: age, dtype: float64

**14.** Calculate the sum of all visits in `df` (i.e. find the total number of visits).

In [179]:
sum(df['visits'])

19

In [180]:
df['visits'].sum()

np.int64(19)

**15.** Calculate the mean age for each different animal in `df`.

In [181]:
df['age'].mean()

np.float64(3.375)

**16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [182]:
row_k = {'animal': ['dog'],
        'age': [7],
        'visits': [1],
        'priority': ['no']}
index_k = ['k']

df_k = pd.DataFrame(data=row_k,index=index_k)

In [183]:
df_k

  animal  age  visits priority
k    dog    7       1       no

In [184]:
pd.merge(df,df_k,how='outer')

/var/folders/00/pdhrm6q934j1lr8wvvq5f8240000gn/T/ipykernel_76867/795069089.py:1: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  pd.merge(df,df_k,how='outer')

   animal  age  visits priority
0     cat  1.5       3       no
1     cat  2.5       1      yes
2     cat  3.0       3      yes
3     cat  NaN       1      yes
4     dog  3.0       1       no
5     dog  5.0       2       no
6     dog  7.0       1       no
7     dog  7.0       2       no
8     dog  NaN       3      yes
9   snake  0.5       2       no
10  snake  4.5       1       no

In [185]:
df.loc['k'] = [5.5, 'dog', 2, 'no']
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    5.5  dog       2       no

In [186]:
df.drop(index='k')

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**17.** Count the number of each type of animal in `df`.

In [187]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
5.5      1
Name: count, dtype: int64

**18.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).

In [188]:
# Sort by 'age' descending, then by 'visits' ascending
df.sort_values(['age', 'visits'], ascending=[False, True])

  animal  age  visits priority
k    5.5  dog       2       no
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

**19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [189]:
df.loc[df['priority'] == 'yes', 'priority'] = True
df.loc[df['priority'] == 'no', 'priority'] = False

In [190]:
df['priority'] = df['priority'].map({'yes':True,'no':False})

In [191]:
df['priority']

a    NaN
b    NaN
c    NaN
d    NaN
e    NaN
f    NaN
g    NaN
h    NaN
i    NaN
j    NaN
k    NaN
Name: priority, dtype: object

**20.** In the 'animal' column, change the 'snake' entries to 'python'.

In [192]:
df.loc[df['animal']=='snake','animal'] = 'python'

In [202]:
df['animal'].replace('python','snake',inplace=True)

/var/folders/00/pdhrm6q934j1lr8wvvq5f8240000gn/T/ipykernel_76867/2564719017.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['animal'].replace('python','snake',inplace=True)

In [208]:
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  0.0       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  0.0       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**21.** For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (*hint: use a pivot table*).

In [206]:
df['age']=df['age'].replace(nan,0)

In [209]:
df.pivot_table(index=['animal'],columns = ['visits'], values=['age'],aggfunc='mean')

         age
visits     1    2    3
animal
cat     1.25  NaN  2.5
dog     3.00  6.0  0.0
snake   4.50  0.5  NaN

## DataFrames: beyond the basics

### Slightly trickier: you may need to combine two or more methods to get the right answer

Difficulty: *medium*

The previous section was tour through some basic but essential DataFrame operations. Below are some ways that you might need to cut your data, but for which there is no single "out of the box" method.

**22.** You have a DataFrame `df` with a column 'A' of integers. For example:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

How do you filter out rows which contain the same integer as the row immediately above?

You should be left with a column containing the following values:

```python
1, 2, 3, 4, 5, 6, 7
```

In [219]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})

In [220]:
df['A'].drop_duplicates()

0    1
1    2
3    3
4    4
5    5
8    6
9    7
Name: A, dtype: int64

**23.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [229]:
df = pd.DataFrame(np.random.random(size=(5, 3)))

In [230]:
df

          0         1         2
0  0.022790  0.890246  0.099875
1  0.434231  0.358663  0.763503
2  0.288311  0.915803  0.434247
3  0.404426  0.938070  0.360545
4  0.980234  0.389068  0.282354

In [233]:
df.sub(df.mean(axis = 1),axis = 0)

          0         1         2
0 -0.314847  0.552609 -0.237762
1 -0.084568 -0.160136  0.244704
2 -0.257810  0.369682 -0.111873
3 -0.163254  0.370390 -0.207135
4  0.429682 -0.161484 -0.268198

**24.** Suppose you have DataFrame with 10 columns of real numbers, for example:

```python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Which column of numbers has the smallest sum?  Return that column's label.

In [234]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))

In [235]:
df

,a,b,c,d,e,f,g,h,i,j
0,0.617037,0.233871,0.482840,0.891748,0.273722,0.121200,0.414577,0.449399,0.470053,0.563113
1,0.940116,0.007451,0.660399,0.905476,0.422752,0.198770,0.986458,0.897701,0.069446,0.894800
2,0.435396,0.432054,0.398208,0.478020,0.607124,0.747274,0.809369,0.983386,0.512565,0.510994
3,0.472227,0.197840,0.078791,0.671438,0.042327,0.950876,0.740114,0.797647,0.706360,0.356674
4,0.850867,0.482364,0.940250,0.934444,0.996460,0.835432,0.861525,0.156378,0.808212,0.706916

In [240]:
df.sum(axis=0)[df.sum(axis=0)==df.sum(axis=0).min()].index

Index(['b'], dtype='object')

**25.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)? As input, use a DataFrame of zeros and ones with 10 rows and 3 columns.

```python
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
```

In [241]:
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
df

   0  1  2
0  0  1  0
1  0  0  0
2  0  0  0
3  1  1  1
4  0  0  0
5  0  0  1
6  0  0  1
7  0  0  1
8  1  1  1
9  0  1  1

In [248]:
len(df.drop_duplicates(keep=0))

2

The next three puzzles are slightly harder.


**26.** In the cell below, you have a DataFrame `df` that consists of 10 columns of floating-point numbers. Exactly 5 entries in each row are NaN values. 

For each row of the DataFrame, find the *column* which contains the *third* NaN value.

You should return a Series of column labels: `e, c, d, h, d`

In [17]:
#import numpy as np

In [53]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

# write a solution to the question here

In [54]:
df

      a   b     c     d     e     f     g     h     i     j
0  0.04 NaN   NaN  0.25   NaN  0.43  0.71  0.51   NaN   NaN
1   NaN NaN   NaN  0.04  0.76   NaN   NaN  0.67  0.76  0.16
2   NaN NaN  0.50   NaN  0.31  0.40   NaN   NaN  0.24  0.01
3  0.49 NaN   NaN  0.62  0.73  0.26  0.85   NaN   NaN   NaN
4   NaN NaN  0.41   NaN  0.05   NaN  0.61   NaN  0.48  0.68

replace all values not NaN in df with 0

In [58]:
(df.isnull().cumsum(axis=1)==3).idxmax(axis=1)

0    e
1    c
2    d
3    h
4    d
dtype: object

In [43]:
df_1 = df.where(df.isnull(), 0)
df_1

     a   b    c    d    e    f    g    h    i    j
0  0.0 NaN  NaN  0.0  NaN  0.0  0.0  0.0  NaN  NaN
1  NaN NaN  NaN  0.0  0.0  NaN  NaN  0.0  0.0  0.0
2  NaN NaN  0.0  NaN  0.0  0.0  NaN  NaN  0.0  0.0
3  0.0 NaN  NaN  0.0  0.0  0.0  0.0  NaN  NaN  NaN
4  NaN NaN  0.0  NaN  0.0  NaN  0.0  NaN  0.0  0.0

In [45]:
df_2 = df_1.where(df.notna(),1)
df_2

     a    b    c    d    e    f    g    h    i    j
0  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0
1  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0
2  1.0  1.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0
3  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0
4  1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0

In [48]:
df_3 = df_2.cumsum(axis=1)
df_3

#print(data_new)

     a    b    c    d    e    f    g    h    i    j
0  0.0  1.0  2.0  2.0  3.0  3.0  3.0  3.0  4.0  5.0
1  1.0  2.0  3.0  3.0  3.0  4.0  5.0  5.0  5.0  5.0
2  1.0  2.0  2.0  3.0  3.0  3.0  4.0  5.0  5.0  5.0
3  0.0  1.0  2.0  2.0  2.0  2.0  2.0  3.0  4.0  5.0
4  1.0  2.0  2.0  3.0  3.0  4.0  4.0  5.0  5.0  5.0

In [51]:
first_3_cols = df_3.eq(3).idxmax(axis=1)
cols = pd.Series(first_3_cols)
cols

0    e
1    c
2    d
3    h
4    d
dtype: object

In [52]:
type(cols)

pandas.core.series.Series

**27.** A DataFrame has a column of groups 'grps' and and column of integer values 'vals': 

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values. You should end up with the answer as follows:
```
grps
a    409
b    156
c    345
```

In [81]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

# write a solution to the question here

In [88]:
df.groupby('grps')['vals'].nlargest(3).groupby(level = 0).sum()

grps
a    409
b    156
c    345
Name: vals, dtype: int64

In [60]:
df

   grps  vals
0     a    12
1     a   345
2     a     3
3     b     1
4     b    45
5     c    14
6     a     4
7     a    52
8     b    54
9     c    23
10    c   235
11    c    21
12    b    57
13    b     3
14    c    87

In [70]:
df_1 = df.groupby('grps').apply(lambda x:x.nlargest(3,'vals'))

/var/folders/00/pdhrm6q934j1lr8wvvq5f8240000gn/T/ipykernel_6059/3345792222.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_1 = df.groupby('grps').apply(lambda x:x.nlargest(3,'vals'))

In [79]:
df_1.reset_index(drop=True,inplace=True)

In [80]:
df_1.groupby('grps')['vals'].sum()

grps
a    409
b    156
c    345
Name: vals, dtype: int64

**28.** The DataFrame `df` constructed below has two integer columns 'A' and 'B'. The values in 'A' are between 1 and 100 (inclusive). 

For each group of 10 consecutive integers in 'A' (i.e. `(0, 10]`, `(10, 20]`, ...), calculate the sum of the corresponding values in column 'B'.

The answer should be a Series as follows:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [89]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

# write a solution to the question here

In [90]:
df

     A   B
0   46  29
1   75  22
2   49  63
3   33  43
4   71  75
..  ..  ..
95  60  87
96  57  40
97  86  19
98  50  56
99  97  94

[100 rows x 2 columns]

In [91]:
bins = pd.cut(df['A'],bins = range (0,101,10))
df.groupby(bins)['B'].sum()

/var/folders/00/pdhrm6q934j1lr8wvvq5f8240000gn/T/ipykernel_6059/2353933766.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(bins)['B'].sum()

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64

## DataFrames: harder problems 

### These might require a bit of thinking outside the box...

...but all are solvable using just the usual pandas/NumPy methods (and so avoid using explicit `for` loops).

Difficulty: *hard*

**29.** Consider a DataFrame `df` where there is an integer column 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be 

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Make this a new column 'Y'.

In [12]:
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

In [14]:
x = (df['X'] != 0).cumsum()
print(x)

0    1
1    2
2    2
3    3
4    4
5    5
6    6
7    6
8    7
9    8
Name: X, dtype: int64

In [15]:
y = x != x.shift()

print(y)

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
8     True
9     True
Name: X, dtype: bool

In [ ]:

x = (df['X'] != 0).cumsum()
y = x != x.shift()
df['Y'] = y.groupby((y != y.shift()).cumsum()).cumsum()

In [11]:
list_y = [1]
for a in range(1,len(df['X'])):
    if df.iloc[a,0] == 0:
        list_y.append(0)
    else:
        list_y.append(list_y[a-1]+1)
df['Y'] = list_y
print(list_y)
print(df)

[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
   X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2

**30.** Consider the DataFrame constructed below which contains rows and columns of numerical data. 

Create a list of the column-row index locations of the 3 largest values in this DataFrame. In this case, the answer should be:
```
[(5, 7), (6, 4), (2, 5)]
```

In [225]:
df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))

**31.** You are given the DataFrame below with a column of group IDs, 'grps', and a column of corresponding integer values, 'vals'.

```python
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
```

Create a new column 'patched_values' which contains the same values as the 'vals' any negative values in 'vals' with the group mean:

```
    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6
```

**32.** Implement a rolling mean over groups with window size 3, which ignores NaN value. For example consider the following DataFrame:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
The goal is to compute the Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. the first window of size three for group 'b' has values 3.0, NaN and 3.0 and occurs at row index 5. Instead of being NaN the value in the new column at this row index should be 3.0 (just the two non-NaN values are used to compute the mean (3+3)/2)

## Series and DatetimeIndex

### Exercises for creating and manipulating Series with datetime data

Difficulty: *easy/medium*

pandas is fantastic for working with dates and times. These puzzles explore some of this functionality.

**33.** Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series `s`.

In [2]:
import pandas as pd
import numpy as np
bdays = pd.date_range(start='2015-01-01', end = '2015-12-31', freq='B')
s=pd.Series(np.random.randn(len(bdays)),index = bdays)

In [3]:
s

2015-01-01   -1.559498
2015-01-02   -0.820524
2015-01-05   -0.292530
2015-01-06    1.490312
2015-01-07   -0.376392
                ...
2015-12-25   -0.803808
2015-12-28    0.298749
2015-12-29   -0.990803
2015-12-30    0.967934
2015-12-31   -0.556069
Freq: B, Length: 261, dtype: float64

**34.** Find the sum of the values in `s` for every Wednesday.

In [5]:
s[s.index.dayofweek==2].sum()

np.float64(-0.6247410384956009)

**35.** For each calendar month in `s`, find the mean of values.

In [8]:
s.resample('ME').sum()

2015-01-31   -1.624155
2015-02-28   -0.848865
2015-03-31    8.863317
2015-04-30    3.058948
2015-05-31    0.868829
2015-06-30    4.068241
2015-07-31    4.026644
2015-08-31    2.752672
2015-09-30    3.143076
2015-10-31    3.563672
2015-11-30   -3.992111
2015-12-31    4.560205
Freq: ME, dtype: float64

**36.** For each group of four consecutive calendar months in `s`, find the date on which the highest value occurred.

In [9]:
s

2015-01-01   -1.559498
2015-01-02   -0.820524
2015-01-05   -0.292530
2015-01-06    1.490312
2015-01-07   -0.376392
                ...
2015-12-25   -0.803808
2015-12-28    0.298749
2015-12-29   -0.990803
2015-12-30    0.967934
2015-12-31   -0.556069
Freq: B, Length: 261, dtype: float64

In [12]:
s.resample('4ME').apply(lambda x:x.idxmax())

2015-01-31   2015-01-23
2015-05-31   2015-05-07
2015-09-30   2015-09-21
2016-01-31   2015-10-23
Freq: 4ME, dtype: datetime64[ns]

In [14]:
s.groupby(pd.Grouper(freq='4ME')).idxmax()

2015-01-31   2015-01-23
2015-05-31   2015-05-07
2015-09-30   2015-09-21
2016-01-31   2015-10-23
Freq: 4ME, dtype: datetime64[ns]

**37.** Create a DateTimeIndex consisting of the third Thursday in each month for the years 2015 and 2016.

In [19]:
tdays = pd.date_range(start='2015-01-01', end = '2016-12-31', freq='WOM-3THU')
tdays

DatetimeIndex(['2015-01-15', '2015-02-19', '2015-03-19', '2015-04-16',
               '2015-05-21', '2015-06-18', '2015-07-16', '2015-08-20',
               '2015-09-17', '2015-10-15', '2015-11-19', '2015-12-17',
               '2016-01-21', '2016-02-18', '2016-03-17', '2016-04-21',
               '2016-05-19', '2016-06-16', '2016-07-21', '2016-08-18',
               '2016-09-15', '2016-10-20', '2016-11-17', '2016-12-15'],
              dtype='datetime64[ns]', freq='WOM-3THU')

In [18]:
s

2015-01-15    0.056376
2015-02-19   -0.252424
2015-03-19    0.817585
2015-04-16    1.846067
2015-05-21   -0.202795
2015-06-18   -0.847607
2015-07-16    0.206446
2015-08-20    0.616239
2015-09-17    0.474785
2015-10-15   -2.388235
2015-11-19   -0.061569
2015-12-17    0.064484
2016-01-21   -0.918925
2016-02-18   -0.890441
2016-03-17   -0.657464
2016-04-21   -0.589734
2016-05-19   -0.856718
2016-06-16   -1.035619
2016-07-21   -0.519560
2016-08-18    0.100221
2016-09-15   -1.181700
2016-10-20    1.199904
2016-11-17    0.592513
2016-12-15   -1.148730
Freq: WOM-3THU, dtype: float64

## Cleaning Data

### Making a DataFrame easier to work with

Difficulty: *easy/medium*

It happens all the time: someone gives you data containing malformed strings, Python, lists and missing data. How do you tidy it up so you can get on with the analysis?

Take this monstrosity as the DataFrame to use in the following puzzles:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
```
Formatted, it looks like this:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


(It's some flight data I made up; it's not meant to be accurate in any way.)

**38.** Some values in the the **FlightNumber** column are missing (they are `NaN`). These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Modify `df` to fill in these missing numbers and make the column an integer column (instead of a float column).

In [3]:
import pandas as pd
import numpy as np

In [66]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

In [5]:
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [67]:
df['FlightNumber'] = df['FlightNumber'].interpolate().astype(int)

**39.** The **From\_To** column would be better as two separate columns! Split each string on the underscore delimiter `_` to give a new temporary DataFrame called 'temp' with the correct values. Assign the correct column names 'From' and 'To' to this temporary DataFrame.

In [75]:
temp = pd.DataFrame()
temp [['from','to']]= df['From_To'].str.split('_',expand = True)

In [69]:
temp.drop(columns = [0,1],inplace = True)

KeyError: '[0, 1] not found in axis'

In [76]:
temp

       from         to
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn

**40.** Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame 'temp'. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

In [90]:
temp = temp.apply(lambda col: col.str.capitalize())

In [94]:
temp.rename(columns = {'from':'From','TO':'To'},inplace=True)

In [95]:
temp

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

**41.** Delete the **From_To** column from `df` and attach the temporary DataFrame 'temp' from the previous questions.

In [96]:
df.drop(columns='From_To',inplace=True)
df

   FlightNumber  RecentDelays              Airline
0         10045      [23, 47]               KLM(!)
1         10055            []    <Air France> (12)
2         10065  [24, 43, 87]  (British Airways. )
3         10075          [13]       12. Air France
4         10085      [67, 32]          "Swiss Air"

In [28]:
df.join(temp)

   FlightNumber  RecentDelays              Airline      From         TO
0         10045      [23, 47]               KLM(!)    London      Paris
1         10055            []    <Air France> (12)    Madrid      Milan
2         10065  [24, 43, 87]  (British Airways. )    London  Stockholm
3         10075          [13]       12. Air France  Budapest      Paris
4         10085      [67, 32]          "Swiss Air"  Brussels     London

In [97]:
df=pd.concat([df,temp],axis=1)

In [98]:
df

   FlightNumber  RecentDelays              Airline      From         To
0         10045      [23, 47]               KLM(!)    London      Paris
1         10055            []    <Air France> (12)    Madrid      Milan
2         10065  [24, 43, 87]  (British Airways. )    London  Stockholm
3         10075          [13]       12. Air France  Budapest      Paris
4         10085      [67, 32]          "Swiss Air"  Brussels     London

In [99]:
front = ['From','TO']
df = df[front + [c for c in df.columns if c not in front]] 
df.rename(columns={'TO':'To'},inplace=True)

KeyError: "['TO'] not in index"

In [100]:
df

   FlightNumber  RecentDelays              Airline      From         To
0         10045      [23, 47]               KLM(!)    London      Paris
1         10055            []    <Air France> (12)    Madrid      Milan
2         10065  [24, 43, 87]  (British Airways. )    London  Stockholm
3         10075          [13]       12. Air France  Budapest      Paris
4         10085      [67, 32]          "Swiss Air"  Brussels     London

**42**. In the **Airline** column, you can see some extra puctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. `'(British Airways. )'` should become `'British Airways'`.

In [101]:
df['Airline']=df['Airline'].str.replace('[^a-zA-Z\s]', '', regex=True).str.strip()

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/var/folders/00/pdhrm6q934j1lr8wvvq5f8240000gn/T/ipykernel_37062/1040355910.py:1: SyntaxWarning: invalid escape sequence '\s'
  df['Airline']=df['Airline'].str.replace('[^a-zA-Z\s]', '', regex=True).str.strip()

In [102]:
df

   FlightNumber  RecentDelays          Airline      From         To
0         10045      [23, 47]              KLM    London      Paris
1         10055            []       Air France    Madrid      Milan
2         10065  [24, 43, 87]  British Airways    London  Stockholm
3         10075          [13]       Air France  Budapest      Paris
4         10085      [67, 32]        Swiss Air  Brussels     London

**43**. In the RecentDelays column, the values have been entered into the DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value should be NaN.

Expand the Series of lists into a DataFrame named `delays`, rename the columns `delay_1`, `delay_2`, etc. and replace the unwanted RecentDelays column in `df` with `delays`.

In [103]:
delays = pd.DataFrame(df['RecentDelays'].tolist())
delays.columns = ['delay_1','delay_2','delay_3'] 
delays

   delay_1  delay_2  delay_3
0     23.0     47.0      NaN
1      NaN      NaN      NaN
2     24.0     43.0     87.0
3     13.0      NaN      NaN
4     67.0     32.0      NaN

In [104]:
df = pd.concat([df,delays],axis= 1)
df
#df.pop('RecentDelays')

,FlightNumber,RecentDelays,Airline,From,To,delay_1,delay_2,delay_3
0,10045,"[23, 47]",KLM,London,Paris,23.0,47.0,NaN
1,10055,[],Air France,Madrid,Milan,NaN,NaN,NaN
2,10065,"[24, 43, 87]",British Airways,London,Stockholm,24.0,43.0,87.0
3,10075,[13],Air France,Budapest,Paris,13.0,NaN,NaN
4,10085,"[67, 32]",Swiss Air,Brussels,London,67.0,32.0,NaN

In [105]:
df_test = df
df_test.pop('RecentDelays')
df_test

,FlightNumber,Airline,From,To,delay_1,delay_2,delay_3
0,10045,KLM,London,Paris,23.0,47.0,NaN
1,10055,Air France,Madrid,Milan,NaN,NaN,NaN
2,10065,British Airways,London,Stockholm,24.0,43.0,87.0
3,10075,Air France,Budapest,Paris,13.0,NaN,NaN
4,10085,Swiss Air,Brussels,London,67.0,32.0,NaN

The DataFrame should look much better now.
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

## Using MultiIndexes

### Go beyond flat DataFrames with additional index levels

Difficulty: *medium*

Previous exercises have seen us analysing data from DataFrames equipped with a single index level. However, pandas also gives you the possibilty of indexing your data using *multiple* levels. This is very much like adding new dimensions to a Series or a DataFrame. For example, a Series is 1D, but by using a MultiIndex with 2 levels we gain of much the same functionality as a 2D DataFrame.

The set of puzzles below explores how you might use multiple index levels to enhance data analysis.

To warm up, we'll look make a Series with two index levels.

**44**. Given the lists `letters = ['A', 'B', 'C']` and `numbers = list(range(10))`, construct a MultiIndex object from the product of the two lists. Use it to index a Series of random numbers. Call this Series `s`.

In [107]:
letters = ['A', 'B', 'C']
numbers = list(range(10))
# Step 1 — Create MultiIndex from product of two lists
idx = pd.MultiIndex.from_product([letters, numbers])

# Step 2 — Create Series of random numbers with MultiIndex
s = pd.Series(np.random.randn(len(idx)), index=idx)

In [108]:
s

A  0    1.781793
   1    0.157777
   2    0.325379
   3    0.135897
   4    0.853195
   5   -0.536720
   6    0.022452
   7    0.092384
   8    0.440457
   9    0.018613
B  0   -0.297000
   1    0.791638
   2   -0.171656
   3    0.721306
   4    0.896359
   5    0.177842
   6   -0.120931
   7    0.065511
   8   -1.289792
   9   -0.511148
C  0    1.531486
   1   -1.314327
   2   -0.100255
   3    1.281552
   4    0.271839
   5    1.013729
   6   -0.279573
   7   -1.036503
   8   -0.063764
   9    0.580997
dtype: float64

**45.** Check the index of `s` is lexicographically sorted (this is a necessary proprty for indexing to work correctly with a MultiIndex).

In [109]:
s.index.is_monotonic_increasing
# True  ✅ — sorted lexicographically
# False ❌ — not sorted

True

**46**. Select the labels `1`, `3` and `6` from the second level of the MultiIndexed Series.

In [112]:
type(s)

pandas.Series

In [114]:
s.loc['A',1:5]

A  1    0.157777
   2    0.325379
   3    0.135897
   4    0.853195
   5   -0.536720
dtype: float64

In [111]:
s.loc[:, [1, 3, 6]]

A  1    0.157777
   3    0.135897
   6    0.022452
B  1    0.791638
   3    0.721306
   6   -0.120931
C  1   -1.314327
   3    1.281552
   6   -0.279573
dtype: float64

**47**. Slice the Series `s`; slice up to label 'B' for the first level and from label 5 onwards for the second level.

In [115]:
s.loc['B',5:]

B  5    0.177842
   6   -0.120931
   7    0.065511
   8   -1.289792
   9   -0.511148
dtype: float64

**48**. Sum the values in `s` for each label in the first level (you should have Series giving you a total for labels A, B and C).

In [118]:
s.groupby(level=0).sum()

A    3.291227
B    0.262130
C    1.885181
dtype: float64

**49**. Suppose that `sum()` (and other methods) did not accept a `level` keyword argument. How else could you perform the equivalent of `s.sum(level=1)`?

**50**. Exchange the levels of the MultiIndex so we have an index of the form (letters, numbers). Is this new Series properly lexsorted? If not, sort it.

In [121]:
new_s = s.swaplevel(0, 1)

if not new_s.index.is_monotonic_increasing:
    new_s = new_s.sort_index()

new_s

0  A    1.781793
   B   -0.297000
   C    1.531486
1  A    0.157777
   B    0.791638
   C   -1.314327
2  A    0.325379
   B   -0.171656
   C   -0.100255
3  A    0.135897
   B    0.721306
   C    1.281552
4  A    0.853195
   B    0.896359
   C    0.271839
5  A   -0.536720
   B    0.177842
   C    1.013729
6  A    0.022452
   B   -0.120931
   C   -0.279573
7  A    0.092384
   B    0.065511
   C   -1.036503
8  A    0.440457
   B   -1.289792
   C   -0.063764
9  A    0.018613
   B   -0.511148
   C    0.580997
dtype: float64

## Minesweeper

### Generate the numbers for safe squares in a Minesweeper grid

Difficulty: *medium* to *hard*

If you've ever used an older version of Windows, there's a good chance you've played with Minesweeper:
- https://en.wikipedia.org/wiki/Minesweeper_(video_game)


If you're not familiar with the game, imagine a grid of squares: some of these squares conceal a mine. If you click on a mine, you lose instantly. If you click on a safe square, you reveal a number telling you how many mines are found in the squares that are immediately adjacent. The aim of the game is to uncover all squares in the grid that do not contain a mine.

In this section, we'll make a DataFrame that contains the necessary data for a game of Minesweeper: coordinates of the squares, whether the square contains a mine and the number of mines found on adjacent squares.

**51**. Let's suppose we're playing Minesweeper on a 5 by 4 grid, i.e.
```
X = 5
Y = 4
```
To begin, generate a DataFrame `df` with two columns, `'x'` and `'y'` containing every coordinate for this grid. That is, the DataFrame should start:
```
   x  y
0  0  0
1  0  1
2  0  2
```

**52**. For this DataFrame `df`, create a new column of zeros (safe) and ones (mine). The probability of a mine occuring at each location should be 0.4.

**53**. Now create a new column for this DataFrame called `'adjacent'`. This column should contain the number of mines found on adjacent squares in the grid. 

(E.g. for the first row, which is the entry for the coordinate `(0, 0)`, count how many mines are found on the coordinates `(0, 1)`, `(1, 0)` and `(1, 1)`.)

**54**. For rows of the DataFrame that contain a mine, set the value in the `'adjacent'` column to NaN.

**55**. Finally, convert the DataFrame to grid of the adjacent mine counts: columns are the `x` coordinate, rows are the `y` coordinate.

## Plotting

### Visualize trends and patterns in data

Difficulty: *medium*

To really get a good understanding of the data contained in your DataFrame, it is often essential to create plots: if you're lucky, trends and anomalies will jump right out at you. This functionality is baked into pandas and the puzzles below explore some of what's possible with the library.

**56.** Pandas is highly integrated with the plotting library matplotlib, and makes plotting DataFrames very user-friendly! Plotting in a notebook environment usually makes use of the following boilerplate:

```python
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')
```

matplotlib is the plotting library which pandas' plotting functionality is built upon, and it is usually aliased to ```plt```.

```%matplotlib inline``` tells the notebook to show plots inline, instead of creating them in a separate window.  

```plt.style.use('ggplot')``` is a style theme that most people find agreeable, based upon the styling of R's ggplot package.

For starters, make a scatter plot of this random data, but use black X's instead of the default markers. 

```df = pd.DataFrame({"xs":[1,5,2,8,1], "ys":[4,2,1,9,6]})```

Consult the [documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html) if you get stuck!

**57.** Columns in your DataFrame can also be used to modify colors and sizes.  Bill has been keeping track of his performance at work over time, as well as how good he was feeling that day, and whether he had a cup of coffee in the morning.  Make a plot which incorporates all four features of this DataFrame.

(Hint:  If you're having trouble seeing the plot, try multiplying the Series which you choose to represent size by 10 or more)

*The chart doesn't have to be pretty: this isn't a course in data viz!*

```
df = pd.DataFrame({"productivity":[5,2,3,1,4,5,6,7,8,3,4,8,9],
                   "hours_in"    :[1,9,6,5,3,9,2,9,1,7,4,2,2],
                   "happiness"   :[2,1,3,2,3,1,2,3,1,2,2,1,3],
                   "caffienated" :[0,0,1,1,0,0,0,0,1,1,0,1,0]})
```

**58.**  What if we want to plot multiple things?  Pandas allows you to pass in a matplotlib *Axis* object for plots, and plots will also return an Axis object.

Make a bar plot of monthly revenue with a line plot of monthly advertising spending (numbers in millions)

```
df = pd.DataFrame({"revenue":[57,68,63,71,72,90,80,62,59,51,47,52],
                   "advertising":[2.1,1.9,2.7,3.0,3.6,3.2,2.7,2.4,1.8,1.6,1.3,1.9],
                   "month":range(12)
                  })
```

Now we're finally ready to create a candlestick chart, which is a very common tool used to analyze stock price data.  A candlestick chart shows the opening, closing, highest, and lowest price for a stock during a time window.  The color of the "candle" (the thick part of the bar) is green if the stock closed above its opening price, or red if below.

![Candlestick Example](img/candle.jpg)

This was initially designed to be a pandas plotting challenge, but it just so happens that this type of plot is just not feasible using pandas' methods.  If you are unfamiliar with matplotlib, we have provided a function that will plot the chart for you so long as you can use pandas to get the data into the correct format.

Your first step should be to get the data in the correct format using pandas' time-series grouping function.  We would like each candle to represent an hour's worth of data.  You can write your own aggregation function which returns the open/high/low/close, but pandas has a built-in which also does this.

The below cell contains helper functions.  Call ```day_stock_data()``` to generate a DataFrame containing the prices a hypothetical stock sold for, and the time the sale occurred.  Call ```plot_candlestick(df)``` on your properly aggregated and formatted stock data to print the candlestick chart.

In [226]:
import numpy as np
def float_to_time(x):
    return str(int(x)) + ":" + str(int(x%1 * 60)).zfill(2) + ":" + str(int(x*60 % 1 * 60)).zfill(2)

def day_stock_data():
    #NYSE is open from 9:30 to 4:00
    time = 9.5
    price = 100
    results = [(float_to_time(time), price)]
    while time < 16:
        elapsed = np.random.exponential(.001)
        time += elapsed
        if time > 16:
            break
        price_diff = np.random.uniform(.999, 1.001)
        price *= price_diff
        results.append((float_to_time(time), price))
    
    
    df = pd.DataFrame(results, columns = ['time','price'])
    df.time = pd.to_datetime(df.time)
    return df

#Don't read me unless you get stuck!
def plot_candlestick(agg):
    """
    agg is a DataFrame which has a DatetimeIndex and five columns: ["open","high","low","close","color"]
    """
    fig, ax = plt.subplots()
    for time in agg.index:
        ax.plot([time.hour] * 2, agg.loc[time, ["high","low"]].values, color = "black")
        ax.plot([time.hour] * 2, agg.loc[time, ["open","close"]].values, color = agg.loc[time, "color"], linewidth = 10)

    ax.set_xlim((8,16))
    ax.set_ylabel("Price")
    ax.set_xlabel("Hour")
    ax.set_title("OHLC of Stock Value During Trading Day")
    plt.show()

**59.** Generate a day's worth of random stock data, and aggregate / reformat it so that it has hourly summaries of the opening, highest, lowest, and closing prices

**60.** Now that you have your properly-formatted data, try to plot it yourself as a candlestick chart.  Use the ```plot_candlestick(df)``` function above, or matplotlib's [```plot``` documentation](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.plot.html) if you get stuck.

*More exercises to follow soon...*